DASHBOARD_GAME_CONFIG = {
  "Pokemon Null 1.1": {
    trainerOrderKey: "null",
    starterGiftGroups: {
      "Starters": ["Chespin", "Fennekin", "Froakie"],
      "Disaster": ["Tornadus", "Thundurus", "Landorus", "Enamorus"],
    },
    importantTrainers: [
      { usageKey: "Leader Roxanne", label: "Leader Roxanne" },
      { usageKey: "Leader Brawly", label: "Leader Brawly" },
      { usageKey: "Leader Wattson", label: "Leader Wattson" },
      { usageKey: "Leader Flannery", label: "Leader Flannery" },
      { usageKey: "Leader Norman", label: "Leader Norman" },
      { usageKey: "Leader Winona", label: "Leader Winona" },
      { usageKey: "Leader Tate", label: "Leader Tate" },
      { usageKey: "Leader Liza", label: "Leader Liza" },
      { usageKey: "Elite Four Sidney", label: "Elite Four Sidney" },
      { usageKey: "Elite Four Phoebe", label: "Elite Four Phoebe" },
      { usageKey: "Elite Four Glacia", label: "Elite Four Glacia" },
      { usageKey: "Elite Four Rival", label: "Elite Four Rival" },
      { usageKey: "Champion Wallace", label: "Champion Wallace" },
    ],
    importantTrainerVariants: [
      {
        label: "Leader Winona",
        usageKey: "Leader Winona",
        variants: [
          { displayName: "Leader Winona 1 |Fortree Gym|" },
          { displayName: "Leader Winona 2 |Fortree Gym|" },
        ],
      },
      {
        label: "Elite Four Sidney",
        usageKey: "Elite Four Sidney",
        variants: [
          { displayName: "Elite Four Sidney Singles |Pokémon League|" },
          { displayName: "Elite Four Sidney Doubles |Pokémon League|" },
        ],
      },
      {
        label: "Elite Four Phoebe",
        usageKey: "Elite Four Phoebe",
        variants: [
          { displayName: "Elite Four Phoebe Singles |Pokémon League|" },
          { displayName: "Elite Four Phoebe Doubles |Pokémon League|" },
        ],
      },
      {
        label: "Elite Four Glacia",
        usageKey: "Elite Four Glacia",
        variants: [
          { displayName: "Ex Elite Four Glacia 1 |Icicle Cave|" },
          { displayName: "Ex Elite Four Glacia 2 |Route 123|" },
        ],
      },
      {
        label: "Elite Four Rival",
        usageKey: "Elite Four Rival",
        variants: [
          { displayName: "Elite Four Rival Singles |Pokémon League|" },
          { displayName: "Elite Four Rival Doubles |Pokémon League|" },
        ],
      },
    ],
  },
  "Renegade Platinum": {
    importantTrainers: [
      { usageKey: "246", label: "Leader Roark" },
      { usageKey: "315", label: "Leader Gardenia" },
      { usageKey: "318", label: "Leader Fantina" },
      { usageKey: "317", label: "Leader Maylene" },
      { usageKey: "316", label: "Leader Wake" },
      { usageKey: "250", label: "Leader Byron" },
      { usageKey: "319", label: "Leader Candice" },
      { usageKey: "320", label: "Leader Volkner" },
      { usageKey: "261", label: "Elite Four Aaron" },
      { usageKey: "262", label: "Elite Four Bertha" },
      { usageKey: "263", label: "Elite Four Flint" },
      { usageKey: "264", label: "Elite Four Lucian" },
      { usageKey: "267", label: "Champion Cynthia" },
    ],
    trainerOrderKey: "rp",
    starterGiftGroups: {
      "Sinnoh Starters": ["Turtwig", "Chimchar", "Piplup"],
      "Kanto Starters": ["Bulbasaur", "Charmander", "Squirtle"],
      "Johto Starters": ["Chikorita", "Cyndaquil", "Totodile"],
      "Hoenn Starters": ["Treecko", "Torchic", "Mudkip"],
      "Eevolutions": ["Flareon", "Vaporeon", "Jolteon", "Espeon", "Umbreon", "Glaceon", "Leafeon"],
      "Fossil": [
        "Kabuto",
        "Omanyte",
        "Lileep",
        "Cranidos",
        "Shieldon",
        "Aerodactyl",
        "Anorith",
      ],
    },
    exactMatchGroups: ["Eevolutions"],
    importantTrainerVariants: [
      {
        label: "Elite Four Aaron",
        usageKey: "261",
        variants: [
          { displayName: "Elite Four Aaron" },
          { displayName: "Elite Four Aaron2" },
          { displayName: "Elite Four Aaron3" },
          { displayName: "Elite Four Aaron4" },
        ],
      },
      {
        label: "Elite Four Bertha",
        usageKey: "262",
        variants: [
          { displayName: "Elite Four Bertha" },
          { displayName: "Elite Four Bertha2" },
          { displayName: "Elite Four Bertha3" },
          { displayName: "Elite Four Bertha4" },
        ],
      },
      {
        label: "Elite Four Flint",
        usageKey: "263",
        variants: [
          { displayName: "Elite Four Flint" },
          { displayName: "Elite Four Flint2" },
          { displayName: "Elite Four Flint3" },
          { displayName: "Elite Four Flint4" },
        ],
      },
      {
        label: "Elite Four Lucian",
        usageKey: "264",
        variants: [
          { displayName: "Elite Four Lucian" },
          { displayName: "Elite Four Lucian2" },
          { displayName: "Elite Four Lucian3" },
          { displayName: "Elite Four Lucian4" },
        ],
      },
      {
        label: "Champion Cynthia",
        usageKey: "267",
        variants: [
          { displayName: "Champion Cynthia" },
          { displayName: "Champion Cynthia2" },
          { displayName: "Champion Cynthia3" },
          { displayName: "Champion Cynthia4" },
        ],
      },
    ],
  },
  "Platinum Kaizo": {
    starterGiftGroups: {
      "Starters": ["Turtwig", "Chimchar", "Piplup"],
      "Poketch Company": ["Glameow", "Meowth", "Skitty"],
      "Eevolutions": ["Flareon", "Vaporeon", "Jolteon", "Espeon", "Umbreon", "Glaceon", "Leafeon"],
      "Veilstone": [
        "Persian",
        "Porygon",
        "Murkrow",
        "Mr. Mime",
        "Pikachu",
        "Voltorb",
        "Pinsir",
        "Phione",
        "Miltank",
        "Castform",
        "Clefairy",
        "Nidoking",
        "Nidoqueen",
        "Magmar",
        "Jynx",
        "Electabuzz",
        "Scyther",
        "Sableye",
        "Ditto",
        "Magneton",
        "Gallade",
        "Misdreavus",
        "Venusaur",
        "Charizard",
        "Blastoise",
        "Hitmontop",
        "Tauros",
        "Dragonite",
      ],
      "Canalave Library": ["Solrock", "Lunatone"],
      "Fossil": [
        "Kabuto",
        "Omanyte",
        "Lileep",
        "Cranidos",
        "Shieldon",
        "Aerodactyl",
        "Anorith",
      ],
      "Contest Hall": [
        "Charizard",
        "Milotic",
        "Kangaskhan",
        "Alakazam",
        "Steelix",
      ],
    },
    exactMatchGroups: ["Eevolutions", "Contest Hall", "Veilstone"],
    importantTrainers: [
      { usageKey: "246", label: "Leader Roark" },
      { usageKey: "315", label: "Leader Gardenia" },
      { usageKey: "318", label: "Leader Fantina" },
      { usageKey: "317", label: "Leader Maylene" },
      { usageKey: "316", label: "Leader Wake" },
      { usageKey: "250", label: "Leader Byron" },
      { usageKey: "319", label: "Leader Candice" },
      { usageKey: "320", label: "Leader Volkner" },
      { usageKey: "866", label: "Elite Four Aaron" },
      { usageKey: "867", label: "Elite Four Bertha" },
      { usageKey: "868", label: "Elite Four Flint" },
      { usageKey: "869", label: "Elite Four Lucian" },
      { usageKey: "870", label: "Champion Cynthia" },
    ],
    trainerOrderKey: "pk",
  },
  "Cascade White": {
    trainerOrderKey: "casc",
  },
  "Emerald Imperium 1.3": {
    importantTrainers: [
      { usageKey: "265", label: "Leader Roxanne" },
      { usageKey: "266", label: "Leader Brawly" },
      { usageKey: "267", label: "Leader Wattson" },
      { usageKey: "268", label: "Leader Flannery" },
      { usageKey: "269", label: "Leader Norman" },
      { usageKey: "270", label: "Leader Winona" },
      { usageKey: "568", label: "Leader Tate" },
      { usageKey: "569", label: "Leader Liza" },
      { usageKey: "272", label: "Leader Juan" },
      { usageKey: "261", label: "Elite Four Sidney" },
      { usageKey: "262", label: "Elite Four Phoebe" },
      { usageKey: "263", label: "Elite Four Glacia" },
      { usageKey: "860", label: "Elite Four Cynthia" },
      { usageKey: "590", label: "Champion Steven With Wallace" },
      { usageKey: "589", label: "Champion Wallace With Steven" },
    ],
    starterGiftGroups: {
      "Starters": [
        "Bulbasaur", "Charmander", "Squirtle",
        "Chikorita", "Cyndaquil", "Totodile",
        "Treecko", "Torchic", "Mudkip",
        "Turtwig", "Chimchar", "Piplup",
        "Snivy", "Tepig", "Oshawott",
        "Chespin", "Fennekin", "Froakie",
        "Rowlet", "Litten", "Popplio",
        "Grookey", "Scorbunny", "Sobble",
        "Sprigatito", "Fuecoco", "Quaxly",
      ],
      "Roamers": [
        "Articuno",
        "Zapdos",
        "Moltres",
        "Raikou",
        "Entei",
        "Suicune",
        "Cresselia",
        "Cobalion",
        "Terrakion",
        "Virizion",
        "Tornadus",
        "Thundurus",
        "Landorus",
        "Keldeo",
        "Calyrex",
        "Enamorus",
      ],
      "Route 109 Seashore House": [
        "Tyrogue",
        "Pansage",
        "Panpour",
        "Pansear",
        "Misdreavus",
        "Pinsir",
        "Heracross",
        "Scyther",
        "Eevee",
        "Magby",
        "Elekid",
        "Smoochum",
        "Riolu",
        "Togepi",
        "Type: Null",
        "Charcadet",
        "Aerodactyl",
      ],
      "Shoal Cave Low Tide Lower Room": [
        "Great Tusk",
        "Scream Tail",
        "Brute Bonnet",
        "Flutter Mane",
        "Slither Wing",
        "Sandy Shocks",
        "Roaring Moon",
        "Walking Wake",
        "Gouging Fire",
        "Raging Bolt",
        "Iron Treads",
        "Iron Bundle",
        "Iron Hands",
        "Iron Jugulis",
        "Iron Moth",
        "Iron Thorns",
        "Iron Valiant",
        "Iron Leaves",
        "Iron Boulder",
        "Iron Crown",
        "Nihilego",
        "Guzzlord",
        "Xurkitree",
        "Buzzwole",
        "Blacephalon",
        "Stakataka",
        "Poipole",
        "Pheromosa",
        "Celesteela",
      ],
      "Victory Road 1F": [
        "Great Tusk",
        "Scream Tail",
        "Brute Bonnet",
        "Flutter Mane",
        "Slither Wing",
        "Sandy Shocks",
        "Roaring Moon",
        "Walking Wake",
        "Gouging Fire",
        "Raging Bolt",
        "Iron Treads",
        "Iron Bundle",
        "Iron Hands",
        "Iron Jugulis",
        "Iron Moth",
        "Iron Thorns",
        "Iron Valiant",
        "Iron Leaves",
        "Iron Boulder",
        "Iron Crown",
        "Nihilego",
        "Guzzlord",
        "Xurkitree",
        "Buzzwole",
        "Blacephalon",
        "Stakataka",
        "Poipole",
        "Pheromosa",
        "Celesteela",
      ],
    },
    importantTrainerVariants: [
      {
        label: "Elite Four Sidney",
        usageKey: "261",
        variants: [
          { displayName: "Elite Four Sidney1" },
          { displayName: "Elite Four Sidney2" },
        ],
      },
      {
        label: "Elite Four Phoebe",
        usageKey: "262",
        variants: [
          { displayName: "Elite Four Phoebe1" },
          { displayName: "Elite Four Phoebe2" },
        ],
      },
      {
        label: "Elite Four Glacia",
        usageKey: "263",
        variants: [
          { displayName: "Elite Four Glacia1" },
          { displayName: "Elite Four Glacia2" },
        ],
      },
    ],
  },
};
