DASHBOARD_GAME_CONFIG = {
  "Renegade Platinum": {
    importantTrainers: [
      { usageKey: "246", label: "Leader Roark" },
      { usageKey: "315", label: "Leader Gardenia" },
      { usageKey: "318", label: "Leader Fantina" },
      { usageKey: "317", label: "Leader Maylene" },
      { usageKey: "316", label: "Leader Wake" },
      { usageKey: "250", label: "Leader Byron" },
      { usageKey: "319", label: "Leader Candice" },
      { usageKey: "320", label: "Leader Volkner" },
      { usageKey: "261", label: "Elite Four Aaron" },
      { usageKey: "262", label: "Elite Four Bertha" },
      { usageKey: "263", label: "Elite Four Flint" },
      { usageKey: "264", label: "Elite Four Lucian" },
      { usageKey: "267", label: "Champion Cynthia" },
    ],
    trainerOrderKey: "rp",
    starterGiftGroups: {
      "Sinnoh Starters": ["Turtwig", "Chimchar", "Piplup"],
      "Kanto Starters": ["Bulbasaur", "Charmander", "Squirtle"],
      "Johto Starters": ["Chikorita", "Cyndaquil", "Totodile"],
      "Hoenn Starters": ["Treecko", "Torchic", "Mudkip"],
      "Eevolutions": ["Flareon", "Vaporeon", "Jolteon", "Espeon", "Umbreon", "Glaceon", "Leafeon"],
    },
    exactMatchGroups: ["Eevolutions"],
  },
  "Platinum Kaizo": {
    importantTrainers: [
      { usageKey: "246", label: "Leader Roark" },
      { usageKey: "315", label: "Leader Gardenia" },
      { usageKey: "318", label: "Leader Fantina" },
      { usageKey: "317", label: "Leader Maylene" },
      { usageKey: "316", label: "Leader Wake" },
      { usageKey: "250", label: "Leader Byron" },
      { usageKey: "319", label: "Leader Candice" },
      { usageKey: "320", label: "Leader Volkner" },
      { usageKey: "866", label: "Elite Four Aaron" },
      { usageKey: "867", label: "Elite Four Bertha" },
      { usageKey: "868", label: "Elite Four Flint" },
      { usageKey: "869", label: "Elite Four Lucian" },
      { usageKey: "870", label: "Champion Cynthia" },
    ],
    trainerOrderKey: "pk",
  },
  "Cascade White": {
    trainerOrderKey: "casc",
  },
  "Emerald Imperium 1.3": {
    starterGiftGroups: {
      "Starters": [
        "Bulbasaur", "Charmander", "Squirtle",
        "Chikorita", "Cyndaquil", "Totodile",
        "Treecko", "Torchic", "Mudkip",
        "Turtwig", "Chimchar", "Piplup",
        "Snivy", "Tepig", "Oshawott",
        "Chespin", "Fennekin", "Froakie",
        "Rowlet", "Litten", "Popplio",
        "Grookey", "Scorbunny", "Sobble",
        "Sprigatito", "Fuecoco", "Quaxly",
      ],
      "Roamers": [
        "Articuno",
        "Zapdos",
        "Moltres",
        "Raikou",
        "Entei",
        "Suicune",
        "Cresselia",
        "Cobalion",
        "Terrakion",
        "Virizion",
        "Tornadus",
        "Thundurus",
        "Landorus",
        "Keldeo",
        "Calyrex",
        "Enamorus"
      ]
    },
  },
};
